### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by Butonix** [jinjaeeon/copy_instagram#1]
Failed to load resource: the server responded with a status of 405 ()
user.js:114 SyntaxError: Unexpected token < in JSON at position 0
/rest-auth/registration/ Failed to load resource: the server responded with a status of 405 ()
user.js:114 SyntaxError: Unexpected token < in JSON at position 0
/rest-auth/registration/ Failed to load resource: the server responded with a status of 405 ()
user.js:114 SyntaxError: Unexpected token < in JSON at position 0
/rest-auth/registration/ Failed to load resource: the server responded with a status of 405 ()
user.js:114 SyntaxError: Unexpected token < in JSON at position 0
/rest-auth/registration/ Failed to load resource: the server responded with a status of 405 ()
user.js:114 SyntaxError: Unexpected token < in JSON at position 0
/rest-auth/registration/ Failed to load resource: the server responded with a status of 405 ()
user.js:114 SyntaxError: Unexpected token < in JSON at position 0
container.js:52 Object
/users/login/facebook/ Failed to load resource: the server responded with a status of 405 ()
user.js:66 SyntaxError: Unexpected token < in JSON at position 0
/copy_instagram/rest-auth/login/ Failed to load resource: the server responded with a status of 405 ()
user.js:89 SyntaxError: Unexpected token < in JSON at position 0
container.js:51 Object
/users/login/facebook/ Failed to load resource: the server responded with a status of 405 ()
user.js:66 SyntaxError: Unexpected token < in JSON at position 0

**Comment by Butonix** [comment]
user.js:95 POST https://jinjaeeon.github.io/rest-auth/registration/ 405 ()
(anonymous) @ user.js:95
(anonymous) @ index.js:11
createAccount @ index.js:13
a._handleSubmit @ container.js:48
i @ react-dom.production.min.js:26
invokeGuardedCallback @ react-dom.production.min.js:25
invokeGuardedCallbackAndCatchFirstError @ react-dom.production.min.js:25
f @ react-dom.production.min.js:30
m @ react-dom.production.min.js:32
z @ react-dom.production.min.js:32
g @ react-dom.production.min.js:31
A @ react-dom.production.min.js:34
qr @ react-dom.production.min.js:93
Oe @ react-dom.production.min.js:70
batchedUpdates @ react-dom.production.min.js:171
$ @ react-dom.production.min.js:54
je @ react-dom.production.min.js:71
user.js:114 SyntaxError: Unexpected token < in JSON at position 0

**Comment by jinjaeeon** [comment]
This does not work. Because I didn't deploy it. I didn't deploy it to AWS. SORRY!!
